name: checks
on: [push]
env:
  PLAYDATE_SDK_VERSION: 1.11.0
  HOME: /Users/runner 
  PLAYDATE_SDK_PATH: /Users/runner/Developer/PlaydateSDK
  PLAYDATE_INSTALLER: /Users/runner/PlaydateSDK.pkg
jobs:
  build_test:
    runs-on: macos-11
    steps:
      - uses: actions/cache@v3
        id: deps-pdsdk
        with:
          path: |
            ${{env.PLAYDATE_SDK_PATH}}
            ${{env.PLAYDATE_INSTALLER}}
          key: PlaydateSDK-${{env.PLAYDATE_SDK_VERSION}}
      - uses: actions/cache@v3
        id: deps-cmocka
        with:
          path: |
            /opt/homebrew/lib
            /opt/homebrew/include
          key: cmocka
      - run: wget https://download.panic.com/playdate_sdk/PlaydateSDK-${{env.PLAYDATE_SDK_VERSION}}.zip
        if: steps.deps-pdsdk.outputs.cache-hit != 'true'
        working-directory: ${{env.HOME}} 
      - run: unzip *.zip
        if: steps.deps-pdsdk.outputs.cache-hit != 'true'
        working-directory: ${{env.HOME}} 
      - run: sudo installer -pkg ${{env.PLAYDATE_INSTALLER}} -target /
        working-directory: ${{env.HOME}} 
      - run: brew install cmocka
        if: steps.deps-cmocka.outputs.cache-hit != 'true'
      - uses: actions/checkout@v2
      - run: make
      - run: make test
