name: checks
on: [push]
env:
  playdate_sdk_version: 1.11.0
jobs:
  build_test:
    runs-on: macos-11
    steps:
      - uses: actions/cache@v3
        id: deps-pdsdk
        with:
          path: ~/Developer/PlaydateSDK
          key: ${{env.playdate_sdk_version}}
      - run: wget https://download.panic.com/playdate_sdk/PlaydateSDK-${{env.playdate_sdk_version}}.zip
        if: steps.deps-pdsdk.outputs.cache-hit != 'true'
      - run: unzip *.zip
        if: steps.deps-pdsdk.outputs.cache-hit != 'true'
      - run: sudo installer -pkg PlaydateSDK-*.pkg -target /
        if: steps.deps-pdsdk.outputs.cache-hit != 'true'
      - run: brew install cmocka
      - uses: actions/checkout@v2
      - run: make
      - run: make test
